version: '3.9'
services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - ${PWD}/config/caddy:/etc/caddy
      - ${PWD}/certs:/etc/certs/ssl:ro
    environment:
      CADDY_WEB_HOST: $CADDY_WEB_HOST
    env_file:
      - env
    networks:
      - ansible-ui

  whoami:
    image: containous/whoami:latest
    container_name: whoami
    networks:
      - ansible-ui

networks:
  ansible-ui:
    driver: bridge